#!/bin/bash
#line 1 is the "shebang" denoting what program should read the file. Line 3 defines the i variable as 1
i=1
#line 4 begins a while loop that is true as long as there is a line to read from the input file
while read -r line  
#line 6 begins a do command, telling the program what to do when the while condition is true
do  
#line 9 defines an if statement that is true as long as the value of the i variable is less than the number at position 1 of the command line arguement.
    if [ "$i" -lt "$1" ] ;
    #lines 11-14 tells the program to "echo" or return the line variable, then sleep for 1 unit of time, and finally increment the value of the i variable by 1 as long as the if statement is true
    then
        echo $line
        sleep 1
        ((i++))
    #lines 16-18 tells the program to echo a message about who made the script if the value of the i variable is equal to the number at position 1 of the command line arguement
    elif [ "$i" -eq "$1" ] ;
    then
    echo "This script was made by Waspinator. Meow!"
    ((i++))
    #lines 20-22 tells the program to break out of the while loop if the if statement is otherwise false
    else 
        break 
    fi
done